// サンプルデータ
import { Recipe, MealSuggestion, MealPreference } from './types';

// サンプルレシピデータ
export const sampleRecipes: Recipe[] = [
  // 主菜
  {
    id: 'r001',
    name: '鶏の照り焼き',
    description: 'ジューシーな鶏もも肉を甘辛いタレで照り焼きにした定番の和食',
    category: '主菜',
    ingredients: [
      { name: '鶏もも肉', amount: '2', unit: '枚', isMain: true },
      { name: '醤油', amount: '大さじ2' },
      { name: 'みりん', amount: '大さじ2' },
      { name: '砂糖', amount: '大さじ1' },
      { name: '酒', amount: '大さじ1' },
      { name: 'しょうが', amount: '1', unit: 'かけ' },
    ],
    steps: [
      { stepNumber: 1, description: '鶏肉は余分な脂を取り除き、フォークで数カ所穴を開ける', duration: 3 },
      { stepNumber: 2, description: '調味料を全て混ぜ合わせてタレを作る', duration: 2 },
      { stepNumber: 3, description: 'フライパンに油を熱し、鶏肉を皮目から焼く', duration: 5 },
      { stepNumber: 4, description: '両面に焼き色がついたら、タレを加えて煮詰める', duration: 8 },
      { stepNumber: 5, description: '鶏肉を取り出し、食べやすい大きさに切る', duration: 2 },
    ],
    cookingTime: 20,
    difficulty: '簡単',
    servings: 2,
    nutrition: {
      calories: 320,
      protein: 28,
      fat: 18,
      carbs: 12,
      salt: 2.1,
    },
    season: '通年',
    tags: ['定番', '子供向け', '作り置き可'],
  },
  {
    id: 'r002',
    name: '肉じゃが',
    description: 'ホクホクのじゃがいもと牛肉の旨味が染み込んだ家庭料理の定番',
    category: '主菜',
    ingredients: [
      { name: '牛肉薄切り', amount: '200', unit: 'g', isMain: true },
      { name: 'じゃがいも', amount: '3', unit: '個', isMain: true },
      { name: '玉ねぎ', amount: '1', unit: '個' },
      { name: 'にんじん', amount: '1/2', unit: '本' },
      { name: 'しらたき', amount: '1', unit: '袋' },
      { name: '醤油', amount: '大さじ3' },
      { name: '砂糖', amount: '大さじ2' },
      { name: 'みりん', amount: '大さじ2' },
      { name: '酒', amount: '大さじ2' },
      { name: 'だし汁', amount: '300', unit: 'ml' },
    ],
    steps: [
      { stepNumber: 1, description: 'じゃがいもは皮を剥き、一口大に切る。玉ねぎはくし切り、にんじんは乱切りにする', duration: 5 },
      { stepNumber: 2, description: 'しらたきは下茹でして、食べやすい長さに切る', duration: 3 },
      { stepNumber: 3, description: '鍋に油を熱し、牛肉を炒める', duration: 3 },
      { stepNumber: 4, description: '野菜を加えて炒め、だし汁と調味料を加える', duration: 5 },
      { stepNumber: 5, description: '落し蓋をして、じゃがいもが柔らかくなるまで煮る', duration: 20 },
    ],
    cookingTime: 36,
    difficulty: '普通',
    servings: 4,
    nutrition: {
      calories: 280,
      protein: 15,
      fat: 8,
      carbs: 35,
      salt: 2.5,
    },
    season: '通年',
    tags: ['定番', '煮物', '作り置き可'],
  },
  
  // 副菜
  {
    id: 'r003',
    name: 'ほうれん草のお浸し',
    description: 'シンプルな味付けでほうれん草の甘みを楽しむ定番の副菜',
    category: '副菜',
    ingredients: [
      { name: 'ほうれん草', amount: '1', unit: '束', isMain: true },
      { name: '醤油', amount: '大さじ1' },
      { name: 'だし汁', amount: '大さじ2' },
      { name: 'かつお節', amount: '適量' },
    ],
    steps: [
      { stepNumber: 1, description: 'たっぷりの湯を沸かし、塩を加える', duration: 3 },
      { stepNumber: 2, description: 'ほうれん草を根元から入れて1分茹でる', duration: 2 },
      { stepNumber: 3, description: '冷水に取り、水気をしっかり絞る', duration: 2 },
      { stepNumber: 4, description: '食べやすい長さに切り、調味料で和える', duration: 2 },
      { stepNumber: 5, description: '器に盛り、かつお節をかける', duration: 1 },
    ],
    cookingTime: 10,
    difficulty: '簡単',
    servings: 2,
    nutrition: {
      calories: 25,
      protein: 3,
      fat: 0.5,
      carbs: 3,
      salt: 0.8,
    },
    season: '冬',
    tags: ['野菜', 'ヘルシー', '時短'],
  },
  {
    id: 'r004',
    name: 'きんぴらごぼう',
    description: '歯ごたえの良いごぼうとにんじんを甘辛く炒めた常備菜',
    category: '副菜',
    ingredients: [
      { name: 'ごぼう', amount: '1', unit: '本', isMain: true },
      { name: 'にんじん', amount: '1/3', unit: '本' },
      { name: '醤油', amount: '大さじ1.5' },
      { name: '砂糖', amount: '大さじ1' },
      { name: 'みりん', amount: '大さじ1' },
      { name: 'ごま油', amount: '大さじ1' },
      { name: '唐辛子', amount: '1', unit: '本' },
      { name: '白ごま', amount: '適量' },
    ],
    steps: [
      { stepNumber: 1, description: 'ごぼうは皮をこそげ、ささがきにして水にさらす', duration: 5 },
      { stepNumber: 2, description: 'にんじんは細切りにする', duration: 2 },
      { stepNumber: 3, description: 'フライパンにごま油を熱し、水気を切ったごぼうとにんじんを炒める', duration: 5 },
      { stepNumber: 4, description: '調味料を加えて、汁気がなくなるまで炒める', duration: 5 },
      { stepNumber: 5, description: '白ごまを振って完成', duration: 1 },
    ],
    cookingTime: 18,
    difficulty: '簡単',
    servings: 4,
    nutrition: {
      calories: 85,
      protein: 2,
      fat: 3,
      carbs: 12,
      salt: 1.0,
    },
    season: '通年',
    tags: ['常備菜', '野菜', '食物繊維'],
  },
  
  // 汁物
  {
    id: 'r005',
    name: '豆腐とわかめの味噌汁',
    description: '定番の具材で作るほっとする味噌汁',
    category: '汁物',
    ingredients: [
      { name: '豆腐', amount: '1/2', unit: '丁', isMain: true },
      { name: 'わかめ（乾燥）', amount: '大さじ1' },
      { name: 'だし汁', amount: '400', unit: 'ml' },
      { name: '味噌', amount: '大さじ2' },
      { name: 'ねぎ', amount: '適量' },
    ],
    steps: [
      { stepNumber: 1, description: 'だし汁を温める', duration: 3 },
      { stepNumber: 2, description: '豆腐を1cm角に切る', duration: 1 },
      { stepNumber: 3, description: 'だし汁に豆腐とわかめを入れる', duration: 2 },
      { stepNumber: 4, description: '火を止めて味噌を溶き入れる', duration: 1 },
      { stepNumber: 5, description: '器に盛り、ねぎを散らす', duration: 1 },
    ],
    cookingTime: 8,
    difficulty: '簡単',
    servings: 2,
    nutrition: {
      calories: 65,
      protein: 5,
      fat: 3,
      carbs: 5,
      salt: 1.8,
    },
    season: '通年',
    tags: ['定番', '時短', 'ヘルシー'],
  },
  {
    id: 'r006',
    name: 'けんちん汁',
    description: '野菜たっぷりの具だくさん汁物',
    category: '汁物',
    ingredients: [
      { name: '大根', amount: '5', unit: 'cm' },
      { name: 'にんじん', amount: '1/3', unit: '本' },
      { name: 'ごぼう', amount: '1/3', unit: '本' },
      { name: '里芋', amount: '2', unit: '個' },
      { name: 'こんにゃく', amount: '1/2', unit: '枚' },
      { name: '豆腐', amount: '1/2', unit: '丁' },
      { name: 'だし汁', amount: '600', unit: 'ml' },
      { name: '醤油', amount: '大さじ2' },
      { name: '塩', amount: '少々' },
      { name: 'ごま油', amount: '大さじ1' },
    ],
    steps: [
      { stepNumber: 1, description: '野菜を全て一口大に切る', duration: 8 },
      { stepNumber: 2, description: 'こんにゃくは下茹でして、一口大に切る', duration: 3 },
      { stepNumber: 3, description: '鍋にごま油を熱し、野菜を炒める', duration: 5 },
      { stepNumber: 4, description: 'だし汁を加えて、野菜が柔らかくなるまで煮る', duration: 15 },
      { stepNumber: 5, description: '豆腐を加え、醤油と塩で味を調える', duration: 3 },
    ],
    cookingTime: 34,
    difficulty: '普通',
    servings: 4,
    nutrition: {
      calories: 95,
      protein: 4,
      fat: 4,
      carbs: 12,
      salt: 1.5,
    },
    season: '冬',
    tags: ['野菜たっぷり', '温まる', '食物繊維'],
  },
  
  // ご飯もの
  {
    id: 'r007',
    name: '鮭おにぎり',
    description: '焼き鮭をほぐして入れた定番のおにぎり',
    category: 'ご飯もの',
    ingredients: [
      { name: 'ご飯', amount: '2', unit: '杯分', isMain: true },
      { name: '鮭', amount: '1', unit: '切れ', isMain: true },
      { name: '塩', amount: '適量' },
      { name: '海苔', amount: '2', unit: '枚' },
    ],
    steps: [
      { stepNumber: 1, description: '鮭を焼いて、骨を取り除いてほぐす', duration: 8 },
      { stepNumber: 2, description: 'ご飯を2等分する', duration: 1 },
      { stepNumber: 3, description: '手に塩をつけて、ご飯の中央に鮭を入れる', duration: 2 },
      { stepNumber: 4, description: '三角形に握る', duration: 2 },
      { stepNumber: 5, description: '海苔を巻く', duration: 1 },
    ],
    cookingTime: 14,
    difficulty: '簡単',
    servings: 2,
    nutrition: {
      calories: 180,
      protein: 8,
      fat: 2,
      carbs: 35,
      salt: 1.0,
    },
    season: '通年',
    tags: ['お弁当', '定番', '朝食'],
  },
  {
    id: 'r008',
    name: '炊き込みご飯',
    description: '具材の旨味が染み込んだ香り豊かなご飯',
    category: 'ご飯もの',
    ingredients: [
      { name: '米', amount: '2', unit: '合', isMain: true },
      { name: '鶏もも肉', amount: '100', unit: 'g' },
      { name: 'にんじん', amount: '1/3', unit: '本' },
      { name: 'しいたけ', amount: '2', unit: '個' },
      { name: 'ごぼう', amount: '1/4', unit: '本' },
      { name: '油揚げ', amount: '1/2', unit: '枚' },
      { name: '醤油', amount: '大さじ2' },
      { name: 'みりん', amount: '大さじ1' },
      { name: '酒', amount: '大さじ1' },
      { name: 'だし汁', amount: '適量' },
    ],
    steps: [
      { stepNumber: 1, description: '米を研いで30分浸水させる', duration: 32 },
      { stepNumber: 2, description: '具材を全て細かく切る', duration: 5 },
      { stepNumber: 3, description: '炊飯器に米、調味料、具材を入れる', duration: 2 },
      { stepNumber: 4, description: 'だし汁を2合の目盛りまで加えて炊く', duration: 40 },
      { stepNumber: 5, description: '炊き上がったら10分蒸らして、混ぜる', duration: 11 },
    ],
    cookingTime: 90,
    difficulty: '普通',
    servings: 4,
    nutrition: {
      calories: 320,
      protein: 10,
      fat: 4,
      carbs: 58,
      salt: 1.2,
    },
    season: '秋',
    tags: ['主食', '一品料理', '季節の味'],
  },
];

// サンプル献立データ
export const sampleMealSuggestion: MealSuggestion = {
  id: 'meal001',
  title: '栄養バランス満点の夕食献立',
  description: '主菜・副菜・汁物の基本的な一汁三菜スタイルで、栄養バランスを考えた献立です',
  recipes: [
    sampleRecipes[0], // 鶏の照り焼き
    sampleRecipes[2], // ほうれん草のお浸し
    sampleRecipes[4], // 豆腐とわかめの味噌汁
  ],
  totalCookingTime: 38,
  totalCalories: 410,
  shoppingList: [
    { ingredient: '鶏もも肉', amount: '2枚', category: '肉・魚' },
    { ingredient: 'ほうれん草', amount: '1束', category: '野菜' },
    { ingredient: '豆腐', amount: '1/2丁', category: 'その他' },
    { ingredient: 'わかめ（乾燥）', amount: '大さじ1', category: 'その他' },
    { ingredient: '醤油', amount: '大さじ4', category: '調味料' },
    { ingredient: 'みりん', amount: '大さじ2', category: '調味料' },
    { ingredient: '砂糖', amount: '大さじ1', category: '調味料' },
    { ingredient: '酒', amount: '大さじ1', category: '調味料' },
    { ingredient: 'しょうが', amount: '1かけ', category: '野菜' },
    { ingredient: 'だし汁', amount: '450ml', category: '調味料' },
    { ingredient: 'かつお節', amount: '適量', category: 'その他' },
    { ingredient: '味噌', amount: '大さじ2', category: '調味料' },
    { ingredient: 'ねぎ', amount: '適量', category: '野菜' },
  ],
  cookingSchedule: [
    { time: '18:00', task: 'ほうれん草を茹でる準備', recipeName: 'ほうれん草のお浸し', duration: 3 },
    { time: '18:03', task: 'ほうれん草を茹でて冷やす', recipeName: 'ほうれん草のお浸し', duration: 4 },
    { time: '18:07', task: 'ほうれん草を切って味付け', recipeName: 'ほうれん草のお浸し', duration: 3 },
    { time: '18:10', task: '鶏肉の下準備', recipeName: '鶏の照り焼き', duration: 3 },
    { time: '18:13', task: '照り焼きのタレを作る', recipeName: '鶏の照り焼き', duration: 2 },
    { time: '18:15', task: '鶏肉を焼き始める', recipeName: '鶏の照り焼き', duration: 5 },
    { time: '18:20', task: 'タレを加えて煮詰める', recipeName: '鶏の照り焼き', duration: 8 },
    { time: '18:28', task: '味噌汁のだし汁を温める', recipeName: '豆腐とわかめの味噌汁', duration: 3 },
    { time: '18:31', task: '豆腐とわかめを加えて味噌を溶く', recipeName: '豆腐とわかめの味噌汁', duration: 5 },
    { time: '18:36', task: '鶏肉を切って盛り付け', recipeName: '鶏の照り焼き', duration: 2 },
    { time: '18:38', task: '全ての料理を配膳', recipeName: '全体', duration: 2 },
  ],
  createdAt: new Date(),
  preference: {
    mealType: '夕食',
    servings: 2,
    cookingTime: '30分以内',
    difficulty: '簡単',
    nutritionFocus: 'バランス重視',
    numberOfDishes: 3,
  },
};

// 一般的な食材リスト（フォーム用）
export const commonIngredients = {
  野菜: ['キャベツ', '玉ねぎ', 'にんじん', 'じゃがいも', 'トマト', 'きゅうり', 'レタス', 'ほうれん草', '大根', 'なす', 'ピーマン', 'もやし', 'ブロッコリー', 'ごぼう', 'れんこん'],
  肉類: ['鶏もも肉', '鶏むね肉', '豚バラ肉', '豚ロース', '豚ひき肉', '牛肉', '牛ひき肉', 'ベーコン', 'ハム', 'ソーセージ'],
  魚介類: ['鮭', 'さば', 'あじ', 'さんま', 'いわし', 'まぐろ', 'えび', 'いか', 'たこ', 'しらす', 'ツナ缶'],
  その他: ['豆腐', '納豆', '卵', '牛乳', 'チーズ', 'ヨーグルト', 'こんにゃく', '油揚げ', '厚揚げ', 'はんぺん'],
};

// アレルギー食材リスト
export const allergyIngredients = ['卵', '乳製品', '小麦', 'そば', '落花生', 'えび', 'かに'];

// 季節の食材
export const seasonalIngredients = {
  春: ['たけのこ', '菜の花', '新玉ねぎ', '新じゃが', 'アスパラガス', 'そら豆', '春キャベツ'],
  夏: ['トマト', 'きゅうり', 'なす', 'ピーマン', 'ゴーヤ', 'オクラ', 'とうもろこし', 'みょうが'],
  秋: ['さつまいも', 'きのこ類', '栗', 'かぼちゃ', 'さんま', '柿', 'ぶどう'],
  冬: ['白菜', '大根', 'ねぎ', 'ほうれん草', 'ブロッコリー', 'カリフラワー', 'みかん'],
};
