# Netlify設定ファイル
[build]
  # ビルドコマンド（Netlify Next.jsプラグイン用）
  command = "npm run build"
  # ビルド出力ディレクトリ（Netlifyプラグイン用）
  publish = "."

[build.environment]
  # Node.jsバージョン
  NODE_VERSION = "18"
  # NPMのキャッシュ無効化を防ぐ
  NPM_FLAGS = "--production=false"
  # 本番環境設定
  NODE_ENV = "production"

# ヘッダー設定（PWA用）
[[headers]]
  for = "/sw.js"
  [headers.values]
    Cache-Control = "no-cache"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# PWAのマニフェストとサービスワーカー用
[[headers]]
  for = "/manifest.json"
  [headers.values]
    Content-Type = "application/manifest+json"
    Cache-Control = "public, max-age=0, must-revalidate"
