@echo off
echo 📱 モバイル献立アプリのセットアップを開始します...

echo Node.jsバージョンを確認中...
node --version

echo npmバージョンを確認中...
npm --version

echo 📦 依存関係をインストール中...
npm install

echo 🔨 アプリケーションをビルド中...
npm run build

echo 🚀 開発サーバーを起動します...
echo ブラウザで http://localhost:3000 を開いてください
npm run dev
